const FIFTY_PER_PAGE = "50";

const BUILD_REQUEST_TIMEOUT_MS = 30000;
const BUILD_REQUEST_MAX_RETRIES = 2;
const BUILD_REQUEST_RETRY_BASE_BACKOFF_MS = 500;

module.exports = {
    FIFTY_PER_PAGE,
    BUILD_REQUEST_TIMEOUT_MS,
    BUILD_REQUEST_MAX_RETRIES,
    BUILD_REQUEST_RETRY_BASE_BACKOFF_MS
};