const DATA_DIR_PATH = "src/data";
const STATIC_CONTENT_DIR_PATH = "src/content";
const DEFAULTS_DIR_PATH = "src/defaults";
const PAGES_DIR_PATH = "src/pages";
const CONTENT_PAGES_PATH_NAME = `content-pages`;
const CONTENT_PAGES_DIR_PATH = `${PAGES_DIR_PATH}/${CONTENT_PAGES_PATH_NAME}`;
const STYLES_DIR_PATH = "src/styles";
const DEFAULT_COLORS_FILE_PATH = `${DEFAULTS_DIR_PATH}/colors.json`;
const COLORS_FILE_PATH = `${DATA_DIR_PATH}/colors.json`;
const COLORS_SCSS_FILE_PATH = `${STYLES_DIR_PATH}/colors.scss`
const FONTS_SCSS_FILE_PATH = `${STYLES_DIR_PATH}/fonts.scss`;
const SITE_SETTINGS_DIR_PATH = `${STATIC_CONTENT_DIR_PATH}/site-settings`;
const SITE_SETTINGS_FILE_PATH = `${SITE_SETTINGS_DIR_PATH}/index.json`;
const MARKETING_PAGE_DIR_PATH = `${STATIC_CONTENT_DIR_PATH}/marketing-page`;
const MARKETING_PAGE_FILE_PATH = `${MARKETING_PAGE_DIR_PATH}/index.json`;
const LOBBY_PAGE_DIR_PATH = `${STATIC_CONTENT_DIR_PATH}/lobby-page`;
const LOBBY_PAGE_FILE_PATH = `${LOBBY_PAGE_DIR_PATH}/index.json`;
const ADS_FILE_PATH = `${STATIC_CONTENT_DIR_PATH}/ads/index.json`;
const NAVBAR_DIR_PATH = `${STATIC_CONTENT_DIR_PATH}/navbar`;
const NAVBAR_FILE_PATH = `${NAVBAR_DIR_PATH}/index.json`;
const FOOTER_DIR_PATH = `${STATIC_CONTENT_DIR_PATH}/footer`;
const FOOTER_FILE_PATH = `${FOOTER_DIR_PATH}/index.json`;
const POSTER_PAGES_FILE_PATH = `${STATIC_CONTENT_DIR_PATH}/posters-pages.json`;
const SUMMIT_FILE_NAME = `summit.json`
const SUMMIT_FILE_PATH = `${DATA_DIR_PATH}/${SUMMIT_FILE_NAME}`;
const EVENTS_FILE_NAME = "events.json";
const EVENTS_FILE_PATH = `${DATA_DIR_PATH}/${EVENTS_FILE_NAME}`;
const EVENTS_IDX_FILE_NAME = "events.idx.json";
const EVENTS_IDX_FILE_PATH = `${DATA_DIR_PATH}/${EVENTS_IDX_FILE_NAME}`;
const SPEAKERS_FILE_NAME = "speakers.json";
const SPEAKERS_FILE_PATH = `${DATA_DIR_PATH}/${SPEAKERS_FILE_NAME}`;
const SPEAKERS_IDX_FILE_NAME = "speakers.idx.json";
const SPEAKERS_IDX_FILE_PATH = `${DATA_DIR_PATH}/${SPEAKERS_IDX_FILE_NAME}`;
const VOTEABLE_PRESENTATIONS_FILE_NAME = "voteable-presentations.json";
const VOTEABLE_PRESENTATIONS_FILE_PATH = `${DATA_DIR_PATH}/${VOTEABLE_PRESENTATIONS_FILE_NAME}`;
const POSTERS_PAGES_FILE_PATH = `${STATIC_CONTENT_DIR_PATH}/posters-pages.json`;
const MARKETING_SETTINGS_FILE_PATH = `${DATA_DIR_PATH}/marketing-settings.json`;
const MAINTENANCE_PATH_NAME = `maintenance`;
const EXPO_HALL_PAGE_FILE_PATH = `${STATIC_CONTENT_DIR_PATH}/expo-hall-page/index.json`;
const INVITATIONS_REJECT_PAGE_FILE_PATH = `${STATIC_CONTENT_DIR_PATH}/invitations-reject-page/index.json`;
const SPONSORS_FILE_NAME = "sponsors.json";
const SPONSORS_FILE_PATH = `${STATIC_CONTENT_DIR_PATH}/${SPONSORS_FILE_NAME}`;
const CMS_FONT_FILE_PATH = "/static/fonts/"
const PAYMENTS_FILE_PATH = `${STATIC_CONTENT_DIR_PATH}/payments.json`;
const APPLE_PAY_DOMAIN_FILE_PATH = `/static/.well-known/`
const APPLE_PAY_DOMAIN_FILE_NAME = `apple-developer-merchantid-domain-association`;

exports.REQUIRED_DIR_PATHS = [
  DATA_DIR_PATH,
  STATIC_CONTENT_DIR_PATH,
  CONTENT_PAGES_DIR_PATH,
  STYLES_DIR_PATH,
  SITE_SETTINGS_DIR_PATH,
  MARKETING_PAGE_DIR_PATH,
  LOBBY_PAGE_DIR_PATH,
  INVITATIONS_REJECT_PAGE_FILE_PATH,
  NAVBAR_DIR_PATH,
  FOOTER_DIR_PATH
];
exports.STATIC_CONTENT_DIR_PATH = STATIC_CONTENT_DIR_PATH;
exports.PAGES_DIR_PATH = PAGES_DIR_PATH;
exports.CONTENT_PAGES_PATH_NAME = CONTENT_PAGES_PATH_NAME;
exports.CONTENT_PAGES_DIR_PATH = CONTENT_PAGES_DIR_PATH;
exports.DEFAULT_COLORS_FILE_PATH = DEFAULT_COLORS_FILE_PATH;
exports.COLORS_FILE_PATH = COLORS_FILE_PATH;
exports.COLORS_SCSS_FILE_PATH = COLORS_SCSS_FILE_PATH;
exports.FONTS_SCSS_FILE_PATH = FONTS_SCSS_FILE_PATH;
exports.SITE_SETTINGS_DIR_PATH = SITE_SETTINGS_DIR_PATH;
exports.SITE_SETTINGS_FILE_PATH = SITE_SETTINGS_FILE_PATH;
exports.MARKETING_PAGE_FILE_PATH = MARKETING_PAGE_FILE_PATH;
exports.LOBBY_PAGE_FILE_PATH = LOBBY_PAGE_FILE_PATH;
exports.ADS_FILE_PATH = ADS_FILE_PATH;
exports.NAVBAR_FILE_PATH = NAVBAR_FILE_PATH;
exports.FOOTER_FILE_PATH = FOOTER_FILE_PATH;
exports.POSTER_PAGES_FILE_PATH = POSTER_PAGES_FILE_PATH;
exports.SUMMIT_FILE_NAME = SUMMIT_FILE_NAME;
exports.SUMMIT_FILE_PATH = SUMMIT_FILE_PATH;
exports.EVENTS_FILE_NAME = EVENTS_FILE_NAME;
exports.EVENTS_FILE_PATH = EVENTS_FILE_PATH;
exports.EVENTS_IDX_FILE_NAME = EVENTS_IDX_FILE_NAME;
exports.EVENTS_IDX_FILE_PATH = EVENTS_IDX_FILE_PATH;
exports.SPEAKERS_FILE_NAME = SPEAKERS_FILE_NAME;
exports.SPEAKERS_FILE_PATH = SPEAKERS_FILE_PATH;
exports.SPEAKERS_IDX_FILE_NAME = SPEAKERS_IDX_FILE_NAME;
exports.SPEAKERS_IDX_FILE_PATH = SPEAKERS_IDX_FILE_PATH;
exports.VOTEABLE_PRESENTATIONS_FILE_NAME = VOTEABLE_PRESENTATIONS_FILE_NAME;
exports.VOTEABLE_PRESENTATIONS_FILE_PATH = VOTEABLE_PRESENTATIONS_FILE_PATH;
exports.POSTERS_PAGES_FILE_PATH = POSTERS_PAGES_FILE_PATH;
exports.MARKETING_SETTINGS_FILE_PATH = MARKETING_SETTINGS_FILE_PATH;
exports.MAINTENANCE_PATH_NAME = MAINTENANCE_PATH_NAME;
exports.EXPO_HALL_PAGE_FILE_PATH = EXPO_HALL_PAGE_FILE_PATH;
exports.INVITATIONS_REJECT_PAGE_FILE_PATH = INVITATIONS_REJECT_PAGE_FILE_PATH;
exports.SPONSORS_FILE_PATH = SPONSORS_FILE_PATH;
exports.CMS_FONT_FILE_PATH = CMS_FONT_FILE_PATH;
exports.PAYMENTS_FILE_PATH = PAYMENTS_FILE_PATH;
exports.APPLE_PAY_DOMAIN_FILE_PATH = APPLE_PAY_DOMAIN_FILE_PATH;
exports.APPLE_PAY_DOMAIN_FILE_NAME = APPLE_PAY_DOMAIN_FILE_NAME;
