const path = require("path");
const fs = require("fs");

const basePackageDir = path.resolve(__dirname, "../..");

const { DEFAULT_COLORS_FILE_PATH } = require("./filePath");
const DEFAULT_COLORS_DATA = require(path.join(basePackageDir, DEFAULT_COLORS_FILE_PATH));

const generateAndWriteScssFile = (generatorFn, data, outputPath) => {
  if (!data || Object.keys(data).length === 0) {
    console.error(`No data provided for SCSS file generation at ${outputPath}.`);
    return;
  }
  const scssFileContent = generatorFn(data);
  if (!scssFileContent) {
    console.error(`Failed to generate content for ${outputPath} SCSS file.`);
    return;
  }
  try {
    // since files are autogenerated, always write them in package scope
    outputPath = path.join(basePackageDir, outputPath);
    fs.writeFileSync(outputPath, scssFileContent);
    console.log(`SCSS file generated successfully at ${outputPath}`);
  } catch (err) {
    console.error(`Error writing SCSS file: ${err.message}`);
  }
};

const getFontFormat = (format) => {
  const formatMap = {
    "ttf": "format(\"truetype\")",
    "otf": "format(\"opentype\")",
    "woff": "format(\"woff\")",
    "woff2": "format(\"woff2\")",
  };
  return formatMap[format] || "";
};

const getFontSrc = (fontPath) => fontPath.replace(/^\/static/, "");

const generateFontFace = (fontFamily, fontData, fontWeight) => {
  if (!fontFamily || !fontData || !fontData.fontFile || !fontData.fontFormat) return "";

  const { fontFile, fontFormat } = fontData;
  return `@font-face {
  font-family: "${fontFamily}";
  src: url("${getFontSrc(fontFile)}") ${getFontFormat(fontFormat)};
  font-weight: ${fontWeight};
}`;
};

const generateFontScssFile = (fontsData) => {
  if (!fontsData || !fontsData.fontFamily || !fontsData.regularFont || !fontsData.boldFont) return null;

  const { fontFamily, regularFont, boldFont } = fontsData;

  if (!regularFont.fontFile || !regularFont.fontFormat) return null;
  if (!boldFont.fontFile || !boldFont.fontFormat) return null;

  const regularFontFace = generateFontFace(fontFamily, regularFont, "normal");
  const boldFontFace = generateFontFace(fontFamily, boldFont, "bold");

  return `$font-family: "${fontFamily}";

:root {
  --font_family: "${fontFamily}" !important;
}

${regularFontFace}
${boldFontFace}
  
%font-regular {
  font-family: var(--font_family);
  font-weight: 400;
}

%font-semi {
  font-family: var(--font_family);
  font-weight: 600;
}

%font-bold {
  font-family: var(--font_family);
  font-weight: 700;
}`;
};

const generateColorsScssFile = (colorsData) => {
  const mergedColorsData = { ...DEFAULT_COLORS_DATA, ...colorsData };

  let colorVars = "";
  for (const [key, value] of Object.entries(mergedColorsData)) {
    colorVars += `$${key}: ${value};\n`;
  }

  const rootColors = `
:root {
  --color_primary: #{$color_primary};
  --color_primary_contrast: #{$color_primary_contrast};
  --color_secondary: #{$color_secondary};
  --color_secondary_contrast: #{$color_secondary_contrast};
  --color_text_dark: #{$color_text_dark};
  --color_text_med: #{$color_text_med};
  --color_text_light: #{$color_text_light};
  --color_background_light: #{$color_background_light};
  --color_background_dark: #{$color_background_dark};
  --color_gray_darker: #{$color_gray_darker};
  --color_gray_dark: #{$color_gray_dark};
  --color_gray_light: #{$color_gray_light};
  --color_gray_lighter: #{$color_gray_lighter};
  --color_input_text_color: #{$color_input_text_color_light};
  --color_input_background_color: #{$color_input_background_color_light};
  --color_input_border_color: #{$color_input_border_color_light};
  --color_text_input_hints: #{$color_text_input_hints_light};
  --color_horizontal_rule: #{$color_horizontal_rule_light};
  --color_icon_light: #{$color_icon_light};
  --color_button_background_color: #{$color_button_background_color};
  --color_button_color: #{$color_button_color};
  --color_alerts: #{$color_alerts};
}`;

  const darkThemeColors = `
html[data-theme="DARK"] {
  --color_text_dark: #{$color_text_light} !important;
  --color_text_light: #{$color_text_dark} !important;
  --color_background_light: #{$color_background_dark} !important;
  --color_background_dark: #{$color_background_light} !important;
  --color_gray_darker: #{$color_gray_lighter} !important;
  --color_gray_dark: #{$color_gray_light} !important;
  --color_gray_light: #{$color_gray_dark} !important;
  --color_gray_lighter: #{$color_gray_darker} !important;
  --color_input_text_color: #{$color_input_text_color_dark} !important;
  --color_input_background_color: #{$color_input_background_color_dark} !important;
  --color_input_border_color: #{$color_input_border_color_dark} !important;
  --color_text_input_hints: #{$color_text_input_hints_dark} !important;
  --color_horizontal_rule: #{$color_horizontal_rule_dark} !important;
}`;

  return `${colorVars}${rootColors}${darkThemeColors}`;
};

module.exports = {
  generateAndWriteScssFile,
  generateFontScssFile,
  generateColorsScssFile
};
